### ISSUE TITLE
Avoid send negative timing to the UI

### ISSUE THREAD

**Issue by latra** [GFWard-Developers/dawe-connectr-pick-ban-ui#1]
In some situations, the timing sent to the UI has a negative value.

This could be caused by the delay between DAWE and the connector, where some miliseconds could be lost. Also, I suspect that there is a "grace period" on the last second during a pick/ban phase. 

Keep sending "0" seconds left will be better than send negative times.

Something could be done on `src/dawe.py`:
```python
    def send_time(self):
        self.status.timer -= 1
        self.send(MyJSONEncoder().encode(Message(self.status)))
```

**Comment by Kashery** [comment]
#3 
take a look that should fix it
